#!C:\Users\SeanS\OneDrive\Attachments\Documents\School\Woodhouse\Computer science NEA\server_pi_image_handling\server\server_env\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
